name: graphes
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation de graphviz
        run: |
          sudo apt update
          sudo apt install -y graphviz

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Rendre ex√©cutable run2.sh
        run: chmod +x ./run2.sh

      - name: Lancement graphviz (tous les fichiers)
        run: ./run2.sh

      - name: Upload de tous les SVG
        uses: actions/upload-artifact@v4
        with:
          name: graphes-svg
          path: ./*.svg

